### ISSUE TITLE
render it with some variables??

### ISSUE THREAD

**Issue by josephsmeng** [syrusakbary/pyjade#101]
is there some way to render it with some variables ?

i tried this:

``` python
import pyjade
s = "title= titleName'"
pyjade.utils.process(s, {'title': 'testPage'})
```

but the output don't render the variables

``` python
u'<title></title>'
```

thanks !

**Comment by nod** [comment]
bump again - I, too, am trying to figure out how to inject variables using  pyjade.utils.process (or some other way)

**Comment by blx** [comment]
Hi everyone, please see my [comment in issue 220](https://github.com/syrusakbary/pyjade/issues/220#issuecomment-158296327) for how to do this.
