### ISSUE TITLE
Using Django {% trans %} with Jade mixins

### ISSUE THREAD

**Issue by takis** [syrusakbary/pyjade#182]
Hi,

I've tried using the Django trans template tag in combination with PyJade's mixin's but I cannot get it to work. I've tried both translating outside of the mixin:
```
mixin button(name, ref)
  a.btn.btn-default(href=ref)
    i.fa.fa-list
      = name

+button("{% trans 'some text' %}", '/some/url/')
```
Which gives the following error:
> Could not parse the remainder: '"{%' from '"{%

And from within the mixin:
```
mixin button(name, ref)
  a.btn.btn-default(href=ref)
    i.fa.fa-list
      | {% trans = name %}

+button('some text', '/some/url/')
```
Which gives the following error:
> Only options for 'trans' are 'noop', 'context "xxx"', and 'as VAR'.

Am I doing it wrong, or is it not supported in PyJade?

**Comment by VovanR** [comment]
Try this:
```
mixin button(name, ref)
  a.btn.btn-default(href=ref)
    i.fa.fa-list
      - trans name

+button('some text', '/some/url/')
```

**Comment by VovanR** [comment]
https://github.com/syrusakbary/pyjade#using-templatetags-and-any-feature-of-the-compiled-to-language

**Comment by takis** [comment]
Thanks! This worked as I had hoped.
