### ISSUE TITLE
Import tag broken inside script tag?

### ISSUE THREAD

**Issue by zeraien** [syrusakbary/pyjade#189]
This syntax should be valid according to Jade spec:
```jade
    script
      include script.js
```

script.js content:
```js
// script.js
console.log('You are awesome');
```
Expected result:
```html
    <script>
      // script.js
      console.log('You are awesome');
    </script>
```

Actual result:
```html
<script>include script.js
</script>
```

**Comment by zeraien** [comment]
Any ideas where I should start looking to fix this? I can probably get a pull request up for it if I can just get some rough idea where to look.

**Comment by blx** [comment]
I believe this was fixed as of June with this commit: https://github.com/syrusakbary/pyjade/commit/8b161f4e6052ec8a1c2eae5f30c78dce411c7137

The jade
```jade
script
  include script.js
```
will now produce the django (for example) template
```html
<script>{% include "script.js" %}
</script>
```
which django would process the way you want, while `script.` would produce the literal
```html
<script>include script.js
</script>
```
