### ISSUE TITLE
Runtime include, filter

### ISSUE THREAD

**Issue by lynncyrin** [syrusakbary/pyjade#196]
Is there a way to use jade to create a jinja2 include or filter that isn't used until runtime?

**Comment by blx** [comment]
Yes. Easy things will be easy, harder things will be more complicated but possible.

The simplest way -- depending on your needs -- would be to just use the pipe prefix for plain text. Passing this template:
```jade
h1 A big
|  {{ "hello"|upper }}
| {% include "a.html" %}
```
into `python2 -m pyjade.convert -c jinja` should spit out this jinja2 template:
```jinja
<h1>A big</h1> {{ "hello"|upper }}
{% include "a.html" %}
```
which is obviously not-yet-jinja-filtered, and which did not throw an error about `upper` not being defined in pyjade.

Is this what you're looking for?

**Comment by LynnCo** [comment]
Exactly what I was looking for, thanks
