### ISSUE TITLE
Example in README doesn't actually work

### ISSUE THREAD

**Issue by kstark** [syrusakbary/pyjade#217]
Due to the removal of special handling for `script` and `style` tags in 8b161f4e, the example in the README no longer compiles correctly.

The README indicates that the jade code
```jade
    script(type='text/javascript')
      if (foo) {
         bar()
      }
```
should compile to
```html
    <script type='text/javascript'>
      if (foo) {
         bar()
      }
    </script>
```
but it actually compiles to
```html
    <script type="text/javascript">}

    </script>
```
instead.

**Comment by blx** [comment]
The one-char PR #209 (open) should fix this! :) Although despite the title of the PR the `.` suffix applies to any tag containing text that shouldn't be parsed.

I think @syrusakbary has been mostly occupied with other projects lately but perhaps we can send him a gentle ping.

**Comment by syrusakbary** [comment]
Merged :) (thanks for the ping @blx)
