### ISSUE TITLE
conflict with angular filter

### ISSUE THREAD

**Issue by codeskyblue** [syrusakbary/pyjade#218]
Can write like

```
span {{"Good" | translate}}
```

**Comment by ericremoreynolds** [comment]
+1

The Angular `{{model_name}}` syntax seems to conflict with some internal representation inside the PyJade compiler (`variable_start_string` and `variable_end_string`) but I haven't been able to figure out exactly how just yet.

**Comment by ericremoreynolds** [comment]
This does not affect the JavaScript jade compiler btw.

**Comment by ericremoreynolds** [comment]
I have worked around the problem like this (I am using pyjade from with Flask, therefore from within Jinja2).

    app.jinja_env.variable_start_string = "{$${"
    app.jinja_env.variable_end_string = "}$$}"
    app.jinja_env.add_extension('pyjade.ext.jinja.PyJadeExtension')

**Comment by codeskyblue** [comment]
Thanks, but it really need docs.
