### ISSUE TITLE
pyjade w/ trans template tag and makemessages

### ISSUE THREAD

**Issue by glassresistor** [syrusakbary/pyjade#244]
I'm trying to figure out if makemessages will work with pyjade and trans.

./manage.py makemessages should output anything marked for translation that lacks into a locales file.  Will this still work if I do this using the pyjade context processors?

**Comment by frgtn** [comment]
I've got it working by specifying `.jade` extension when invoking `makemessages` like this: `./manage.py makemessages -e html,jade,py,txt`

**Comment by glassresistor** [comment]
thanks
