### ISSUE TITLE
go110warning with Django 1.9.6

### ISSUE THREAD

**Issue by MalikKeio** [syrusakbary/pyjade#256]
I tried fiddling with Django today for the first time and thought about using jade templates. That is when I found pyjade.

The following warning, indicating a future change in Django's API, is raised in the console at the first request:

    /home/...../python3.5/site-packages/django/template/engine.py:123: RemovedInDjango110Warning: pyjade.ext.django.Loader inherits from django.template.loader.BaseLoader instead of django.template.loaders.base.Loader. 
      loader = self.find_template_loader(template_loader)

This is nothing serious, I just thought to let you know, just in case. Otherwise, it works like a charm!

**Comment by bjesus** [comment]
Django 1.10 was released yesterday. Is PyJade still being developed?..

**Comment by hmleal** [comment]
Please look the pull request #263 💃

**Comment by syrusakbary** [comment]
Merged! :)
