### ISSUE TITLE
Clarify filter registration

### ISSUE THREAD

**Issue by jamescasbon** [syrusakbary/pyjade#26]
Hi, I successfully registered markdown/coffeescript filters with 

``` python
import coffeescript 
import markdown
pyjade.compiler.Compiler.filters['coffeescript'] = lambda x,y: coffeescript.compile(x)
pyjade.compiler.Compiler.filters['markdown'] = lambda x,y: markdown.markdown(x, output_format='html5')
```

Is this the correct way, is there an API I'm missing?

You might consider registering these two if the libraries are available.

**Comment by karland** [comment]
Could you give an example please how you would now register `coffeescript`and `markdown`. That would be great. Thanks.
