### ISSUE TITLE
Pyjade problem import BaseLoader on Django 1.10

### ISSUE THREAD

**Issue by slaveofcode** [syrusakbary/pyjade#261]
I just upgraded my django version from 1.9 into 1.10, before i did this all is going well

it seems the `BaseLoader` was changed into `Loader` on django 1.10

here's the details:

    Exception Type:	InvalidTemplateLibrary
    Exception Value:	Invalid template library specified. ImportError raised when trying to load 'pyjade.ext.django.templatetags': cannot import name 'BaseLoader'
    Exception Location:	/home/aditya/.../venv/lib/python3.4/site-packages/django/template/library.py in import_library, line 325

**Comment by hmleal** [comment]
Please look the pull request #263 💃

**Comment by hmleal** [comment]
Please closes this issue. Solved with pull request #263

**Comment by kakulukia** [comment]
could you please release a new version, where this is fixed? @slaveofcode @syrusakbary
