### ISSUE TITLE
Unable to use dict in tag

### ISSUE THREAD

**Issue by pikeas** [syrusakbary/pyjade#28]
I have code like this:

for item in items
    option(value='#{item.data}') #{item.data}

The second item.data works, but the first does not. Django produces an AttributeError: 'dict' object has no attribute 'data'. I've tried:

value=item.data
value='#{item.data}'
value="#{item.data}"
value!=item.data

and a few other combinations, but none of them work. Is this a bug, or is different syntax needed to access a dict while in a tag?

**Comment by zeraien** [comment]
This works too: 
```jade
a(href="{{item.data}}")
```
