### ISSUE TITLE
trans and blocktrans not processed by makemessages in django

### ISSUE THREAD

**Issue by iceripple** [syrusakbary/pyjade#37]
Django's makemessages management command does not collect strings for translation under
 -trans
or
 -blocktrans

No idea if that is even possible.

workaround is to use original django style tags {% trans %} and {%blocktrans%}

**Comment by carlware** [comment]
I have the same issue but using django 1.7.4 I tried adding ```import pyjade.ext.django``` to ```__init__.py``` and adding 'pyjade.ext.django' to INSTALLED_APPS. Any idea ?

**Comment by jmp0xf** [comment]
I met the same problem. Deeply custom tags are huge hazards in a black box working with various Django backend. A less intrusive method is more appealing, say pre-processing the custom tags.
