### ISSUE TITLE
filename of `extends` statement should be fixed to html

### ISSUE THREAD

**Issue by reorx** [syrusakbary/pyjade#56]
Content of `ext.jade`

```
extends layout
```

Output of `pyjade ext.jade`

```
{% extends "layout.jade" %}
```

I think it's better to get `layout.html` than `layout.jade` since `layout.jade` will also be converted into html.

**Comment by towry** [comment]
Doesn't work if the extension of jade template is `pug`.

**Comment by towry** [comment]
I looked in the source of `compiler.py` and saw those lines:

```
def format_path(self,path):
        has_extension = '.' in os.path.basename(path)
        if not has_extension:
            path += self.extension
        return path

    def visitExtends(self,node):
        path = self.format_path(node.path)
        print path
        self.buffer('{%% extends "%s" %%}' % (path))
```

How come the extends path in jade does not have an extension? Now jade has a new extension name `pug`, I think this should be fixed.
